### ISSUE TITLE
Is the ndarray schema unreasonably coupled to numpy?

### ISSUE THREAD

**Issue by eslavich** [asdf-format/asdf-standard#260]
The ndarray schema is convenient for serializing numpy arrays, but I'm concerned about support for np.recarray.  The schema allows unlimited nested datatypes to represent what is essentially a table posing as an array.  Since we already have a separate [schema](https://github.com/asdf-format/asdf-standard/blob/1.5.0/schemas/stsci.edu/asdf/core/table-1.0.0.yaml) for serializing a table, I wonder if we ought to limit ndarray to only homogeneous arrays of a single scalar datatype.

@perrygreenfield @jdavies-st

**Comment by perrygreenfield** [comment]
Yes, that is a potential problem. Is there any existing use of that in the pipelines?

**Comment by nden** [comment]
Would serializing a FITS binary table fall under this? If so, yes, I believe it is used in the pipeline but can be changed. Table serialization has always been problematic in the pipeline although I can't give examples of problems now, I'll have to look them up.

**Comment by eslavich** [comment]
> Would serializing a FITS binary table fall under this? 

Yes, here's an example of a simple FITS binary table as serialized by ASDF:

```
data: !core/ndarray-1.0.0
  source: 0
  datatype:
  - byteorder: big
    datatype: [ascii, 18]
    name: COMPNAME
  - byteorder: big
    datatype: [ascii, 11]
    name: KEYWORD
  - {byteorder: big, datatype: int32, name: INNODE}
  - {byteorder: big, datatype: int32, name: OUTNODE}
  - byteorder: big
    datatype: [ascii, 17]
    name: THCOMPNAME
  - byteorder: big
    datatype: [ascii, 68]
    name: COMMENT
  byteorder: big
  shape: [3689]
```
