### ISSUE TITLE
`items` usage is `asdf-1.1.0` `history_entry` fails to validate items beyond the first

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf-standard#436]
https://github.com/asdf-format/asdf-standard/blob/c367d14fae4b5155679e2c40b531140586e25daf/resources/schemas/stsci.edu/asdf/core/asdf-1.1.0.yaml#L43-L50

Since the `items` value is a list (instead of an object) and there is no `additionalItems` the draft 4 defines this behavior:
https://json-schema.org/draft-04/draft-fge-json-schema-validation-00#rfc.section.8.2.3.2
as validating only the first item in the list against the schema (since there's only 1 schema in the list).

A similar issue exists with the "backwards compatible" part of the same schema:
https://github.com/asdf-format/asdf-standard/blob/c367d14fae4b5155679e2c40b531140586e25daf/resources/schemas/stsci.edu/asdf/core/asdf-1.1.0.yaml#L24-L27

Loading an ASDF file (hand edited) that includes:
```yaml
history:
  extensions:
  - !core/extension_metadata-1.0.0
    extension_class: asdf.extension._manifest.ManifestExtension
    extension_uri: asdf://asdf-format.org/core/extensions/core-1.5.0
    manifest_software: !core/software-1.0.0 {name: asdf_standard, version: 1.0.4.dev187+g1458b25}
    software: !core/software-1.0.0 {name: asdf, version: 3.0.2.dev112+g143eb2d9}
  - some random stuff
  - 1
```
passes validation when the file is opened (but does fail when asdf attempts to check these history entries with a `AttributeError: 'str' object has no attribute 'extension_uri'`).
