### ISSUE TITLE
ndarray mask describes filling values when a scalar is present

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf-standard#452]
From:
https://github.com/asdf-format/asdf-standard/blob/14ceba9dbe31044417fe400ed8db6b872b02c26c/resources/schemas/stsci.edu/asdf/core/ndarray-1.1.0.yaml#L372-L378

> If a scalar number, that number is used to represent missing values. 

This means that the following:
```yaml
#ASDF 1.0.0
#ASDF_STANDARD 1.6.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.1.0
ma: !core/ndarray-1.1.0
  data: [1, 2]
  mask: 2
  datatype: int64
...
```
opens as:
```
masked_array(data=[1, --],
             mask=[False,  True],
       fill_value=2)
```
I can't find a way in the python implementation of asdf to generate a file with this structure.
